#!/bin/bash
# =============================================================================
# Minecraft Create+ Server Start Script
# MC 1.19.2 | Forge 43.5.1
# =============================================================================
# Memory: adjust -Xmx based on your hardware
#   Pi 4 (4GB): -Xmx2560M  (Create is heavy, Pi 4 may struggle)
#   Pi 4 (8GB): -Xmx4G
#   Pi 5 (8GB): -Xmx5G
# =============================================================================

MAX_MEMORY="${MAX_MEMORY:-4G}"
MIN_MEMORY="${MIN_MEMORY:-2G}"

# Creeper Firework: damage entities/players but do NOT break blocks
mkdir -p /server/config
if [ ! -f /server/config/creeper_firework-common.toml ]; then
cat > /server/config/creeper_firework-common.toml << 'EOF'
[creeper_firework]
	#[Default: true]
	enabled = true

	#Whether the creeper explosion breaks blocks.
	#[Default: false]
	breakBlocks = false

	#Whether the creeper explosion damages entities and players.
	#[Default: false]
	damageEntities = true
EOF
fi

echo "Starting Create+ server with ${MAX_MEMORY} max memory..."

# Forge server is launched via the @args file generated by the installer
exec java \
    -Xms${MIN_MEMORY} \
    -Xmx${MAX_MEMORY} \
    -XX:+UseG1GC \
    -XX:+ParallelRefProcEnabled \
    -XX:MaxGCPauseMillis=200 \
    -XX:+UnlockExperimentalVMOptions \
    -XX:+DisableExplicitGC \
    -XX:G1NewSizePercent=30 \
    -XX:G1MaxNewSizePercent=40 \
    -XX:G1HeapRegionSize=8M \
    -XX:G1ReservePercent=20 \
    -XX:G1HeapWastePercent=5 \
    -XX:G1MixedGCCountTarget=4 \
    -XX:InitiatingHeapOccupancyPercent=15 \
    -XX:G1MixedGCLiveThresholdPercent=90 \
    -XX:G1RSetUpdatingPauseTimePercent=5 \
    -XX:SurvivorRatio=32 \
    -XX:+PerfDisableSharedMem \
    -XX:MaxTenuringThreshold=1 \
    -Dusing.aikars.flags=https://mcflags.emc.gs \
    -Daikars.new.flags=true \
    @libraries/net/minecraftforge/forge/1.19.2-43.5.1/unix_args.txt \
    nogui
