#!/bin/bash
# =============================================================================
# Minecraft Create+ Server Start Script
# MC 1.21.1 | NeoForge 21.1.228
# =============================================================================
# Memory: adjust -Xmx based on your hardware
#   Pi 4 (4GB): -Xmx2560M  (Create is heavy, Pi 4 may struggle)
#   Pi 4 (8GB): -Xmx4G
#   Pi 5 (8GB): -Xmx5G
# =============================================================================

MAX_MEMORY="${MAX_MEMORY:-4G}"
MIN_MEMORY="${MIN_MEMORY:-2G}"

echo "Starting Create+ server with ${MAX_MEMORY} max memory..."

# NeoForge server is launched via the @args file generated by the installer
exec java \
    -Xms${MIN_MEMORY} \
    -Xmx${MAX_MEMORY} \
    -XX:+UseG1GC \
    -XX:+ParallelRefProcEnabled \
    -XX:MaxGCPauseMillis=200 \
    -XX:+UnlockExperimentalVMOptions \
    -XX:+DisableExplicitGC \
    -XX:G1NewSizePercent=30 \
    -XX:G1MaxNewSizePercent=40 \
    -XX:G1HeapRegionSize=8M \
    -XX:G1ReservePercent=20 \
    -XX:G1HeapWastePercent=5 \
    -XX:G1MixedGCCountTarget=4 \
    -XX:InitiatingHeapOccupancyPercent=15 \
    -XX:G1MixedGCLiveThresholdPercent=90 \
    -XX:G1RSetUpdatingPauseTimePercent=5 \
    -XX:SurvivorRatio=32 \
    -XX:+PerfDisableSharedMem \
    -XX:MaxTenuringThreshold=1 \
    -Dusing.aikars.flags=https://mcflags.emc.gs \
    -Daikars.new.flags=true \
    @libraries/net/neoforged/neoforge/21.1.228/unix_args.txt \
    nogui
